from django.db import models
from django.conf import settings


class MealPlan(models.Model):
    """Stores a personalized 7-day meal plan generated by AI."""
    GOAL_CHOICES = [
        ('weight_loss', 'Weight Loss'),
        ('muscle_gain', 'Muscle Gain'),
        ('diabetes_management', 'Diabetes Management'),
        ('heart_health', 'Heart Health'),
        ('general_wellness', 'General Wellness'),
    ]
    DIET_CHOICES = [
        ('vegetarian', 'Vegetarian'),
        ('vegan', 'Vegan'),
        ('non_veg', 'Non-Vegetarian'),
        ('eggetarian', 'Eggetarian'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='meal_plans'
    )
    goal = models.CharField(max_length=30, choices=GOAL_CHOICES, default='general_wellness')
    dietary_preference = models.CharField(max_length=20, choices=DIET_CHOICES, default='vegetarian')
    allergies = models.TextField(blank=True, default='', help_text='Comma-separated list of food allergies')
    calorie_target = models.PositiveIntegerField(null=True, blank=True, help_text='Optional daily calorie target')
    plan_data = models.JSONField(default=dict, help_text='Structured 7-day plan from AI')
    ai_notes = models.TextField(blank=True, default='', help_text='General AI recommendations')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.get_goal_display()} Plan — {self.user.username} — {self.created_at.strftime('%b %d, %Y')}"
