# Generated by Django 6.0.6 on 2026-07-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_scans/')),
                ('food_name', models.CharField(blank=True, default='', max_length=200)),
                ('calories', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=6, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=6, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=6, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=6, null=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=20)),
                ('ai_analysis', models.TextField(blank=True, default='', help_text='Full AI analysis response')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
