# Generated by Django 6.0.6 on 2026-07-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], default=3)),
                ('journal_text', models.TextField(blank=True, default='', help_text='Write about your day')),
                ('activities', models.CharField(blank=True, default='', help_text='Comma-separated tags (e.g., exercise, work, social)', max_length=300)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Hours of sleep last night', max_digits=3, null=True)),
                ('ai_sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='', max_length=20)),
                ('ai_analysis', models.TextField(blank=True, default='', help_text='AI mental health insights')),
                ('entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
    ]
