# Generated by Django 6.0.6 on 2026-07-03 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('blood_pressure', 'Blood Pressure (mmHg)'), ('blood_sugar', 'Blood Sugar (mg/dL)'), ('heart_rate', 'Heart Rate (bpm)'), ('temperature', 'Temperature (°F)'), ('spo2', 'SpO2 (%)')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, help_text='Primary value (systolic for BP)', max_digits=7)),
                ('secondary_value', models.DecimalField(blank=True, decimal_places=2, help_text='Secondary value (diastolic for BP, leave blank for other metrics)', max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
