# Generated by Django 6.0.6 on 2026-07-03 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_area', models.CharField(blank=True, default='', max_length=50)),
                ('symptoms_json', models.TextField(default='[]', help_text='JSON array of selected symptoms')),
                ('additional_info', models.TextField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('severity', models.IntegerField(default=5, help_text='1-10 scale')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('ai_response', models.TextField(blank=True, default='')),
                ('urgency_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='', max_length=20)),
                ('possible_conditions', models.TextField(blank=True, default='', help_text='JSON array of possible conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
