# Generated by Django 6.0.6 on 2026-07-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('diabetes_management', 'Diabetes Management'), ('heart_health', 'Heart Health'), ('general_wellness', 'General Wellness')], default='general_wellness', max_length=30)),
                ('dietary_preference', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('non_veg', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian')], default='vegetarian', max_length=20)),
                ('allergies', models.TextField(blank=True, default='', help_text='Comma-separated list of food allergies')),
                ('calorie_target', models.PositiveIntegerField(blank=True, help_text='Optional daily calorie target', null=True)),
                ('plan_data', models.JSONField(default=dict, help_text='Structured 7-day plan from AI')),
                ('ai_notes', models.TextField(blank=True, default='', help_text='General AI recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
