# Generated by Django 6.0.6 on 2026-07-16 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_type', models.CharField(choices=[('text', 'Text'), ('document', 'Document'), ('voice', 'Voice')], default='text', max_length=10)),
                ('source_language', models.CharField(default='Auto-Detect', max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('original_text', models.TextField(blank=True, default='')),
                ('translated_text', models.TextField(blank=True, default='')),
                ('plain_explanation', models.TextField(blank=True, default='', help_text='Plain-language explanation of medical jargon.')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='translator/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Translation histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
